-- AlterTable
ALTER TABLE "public"."StickyNote" ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 200,
ADD COLUMN     "posX" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "posY" INTEGER NOT NULL DEFAULT 50,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 200;
