import PDFDocument from "pdfkit";
import { ExpenseCheck, PaymentMode } from "@prisma/client";

export interface LPOData {
  agentName: string;
  kraPin?: string | null;
  candidateName?: string;
  clientName?: string;
  date: Date;
  expenseCheck?: ExpenseCheck;
  expenseName?: string;
  expenseDescription: string;
  institutionName: string;
  paymentMode: PaymentMode;
  paymentModeDescription: string;
  amount: number;
  currency: string;
  totalAmountPaid: number;
  type?: "CLIENT" | "OPERATIONAL"; // Made optional to fix TS2345
}

export const generateLPOPdf = async (
    expense: LPOData,
    lpoNumber: string
): Promise<{ pdfBuffer: Buffer; fileName: string }> => {
  const doc = new PDFDocument({ margin: 50 });
  const buffers: Buffer[] = [];
  doc.on("data", buffers.push.bind(buffers));
  doc.on("end", () => {});

  // Header
  doc.fontSize(20).font("Helvetica-Bold").text("Local Purchase Order (LPO)", { align: "center" });
  doc.moveDown(1.5);
  doc.fontSize(12).font("Helvetica").text(`LPO Number: ${lpoNumber}`, 50, 100);
  doc.text(`Date Issued: ${expense.date.toISOString().split("T")[0]}`, 50, 120);
  doc.text(`Type: ${expense.type || "General Expense"}`, 50, 140); // Fallback for undefined type

  // Supplier/Agent Details
  doc.moveDown(1);
  doc.font("Helvetica-Bold").text("Supplier Details:", 50, 160, { underline: true });
  doc.font("Helvetica").text(`Agent: ${expense.agentName}`, 50, 180);
  if (expense.kraPin) {
    doc.text(`KRA PIN: ${expense.kraPin}`, 50, 200);
  }

  // Expense Details
  doc.moveDown(1);
  doc.font("Helvetica-Bold").text("Expense Details:", 50, 240, { underline: true });
  doc.font("Helvetica");
  if (expense.candidateName) {
    doc.text(`Candidate: ${expense.candidateName}`, 50, 260);
  }
  if (expense.clientName) {
    doc.text(`Client: ${expense.clientName}`, 50, 280);
  }
  doc.text(`Institution: ${expense.institutionName}`, 50, 300);
  if (expense.expenseCheck) {
    doc.text(`Check: ${expense.expenseCheck}`, 50, 320);
  }
  if (expense.expenseName) {
    doc.text(`Expense Name: ${expense.expenseName}`, 50, 340);
  }
  doc.text(`Description: ${expense.expenseDescription}`, 50, 360);
  doc.text(`Payment Mode: ${expense.paymentMode}`, 50, 380);
  doc.text(`Payment Description: ${expense.paymentModeDescription}`, 50, 400);
  doc.text(`Amount: ${expense.currency} ${expense.amount.toFixed(2)}`, 50, 420);
  doc.text(`Total Amount Paid: ${expense.currency} ${expense.totalAmountPaid.toFixed(2)}`, 50, 440);

  // Footer
  doc.moveDown(2);
  doc.fontSize(10).text("Generated by Expense Management System", { align: "center" });

  doc.end();
  const pdfBuffer = await new Promise<Buffer>((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(buffers)));
  });

  const fileName = `lpo-${lpoNumber.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`;

  return { pdfBuffer, fileName };
};